In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
sentence=['the glass of milk',
          'the glass of juice',
          'the cup of tea',
          'i am a good boy',
          'i am a good developer',
          'understand the meaning of words',
          'your videos are good']


In [25]:
voc_size=10000

In [26]:
one_hot_rep=[one_hot(words,voc_size)for words in sentence]

In [27]:
one_hot_rep

[[3608, 6002, 640, 2758],
 [3608, 6002, 640, 3381],
 [3608, 4853, 640, 7896],
 [904, 6687, 7831, 5148, 7744],
 [904, 6687, 7831, 5148, 7184],
 [9513, 3608, 3859, 640, 3938],
 [2501, 4040, 2984, 5148]]

In [28]:
sentence

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [29]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [30]:
import numpy as np
 

In [31]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3608 6002  640 2758]
 [   0    0    0    0 3608 6002  640 3381]
 [   0    0    0    0 3608 4853  640 7896]
 [   0    0    0  904 6687 7831 5148 7744]
 [   0    0    0  904 6687 7831 5148 7184]
 [   0    0    0 9513 3608 3859  640 3938]
 [   0    0    0    0 2501 4040 2984 5148]]


In [32]:
dim=10

In [35]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [36]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


array([[[-1.27129667e-02, -3.47139835e-02,  3.42463367e-02,
          2.25774981e-02,  1.19847059e-03,  1.92240737e-02,
         -8.12556595e-03, -1.78078040e-02, -1.01359934e-03,
         -4.44382802e-02],
        [-1.27129667e-02, -3.47139835e-02,  3.42463367e-02,
          2.25774981e-02,  1.19847059e-03,  1.92240737e-02,
         -8.12556595e-03, -1.78078040e-02, -1.01359934e-03,
         -4.44382802e-02],
        [-1.27129667e-02, -3.47139835e-02,  3.42463367e-02,
          2.25774981e-02,  1.19847059e-03,  1.92240737e-02,
         -8.12556595e-03, -1.78078040e-02, -1.01359934e-03,
         -4.44382802e-02],
        [-1.27129667e-02, -3.47139835e-02,  3.42463367e-02,
          2.25774981e-02,  1.19847059e-03,  1.92240737e-02,
         -8.12556595e-03, -1.78078040e-02, -1.01359934e-03,
         -4.44382802e-02],
        [ 3.97885554e-02,  8.18595290e-05, -2.96142343e-02,
          3.56568731e-02, -4.90305200e-02, -4.94892001e-02,
          4.91443314e-02, -2.06935890e-02,  3.761763

In [38]:
embedded_docs[0]

array([   0,    0,    0,    0, 3608, 6002,  640, 2758], dtype=int32)

In [43]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[-1.27129667e-02, -3.47139835e-02,  3.42463367e-02,
         2.25774981e-02,  1.19847059e-03,  1.92240737e-02,
        -8.12556595e-03, -1.78078040e-02, -1.01359934e-03,
        -4.44382802e-02],
       [-1.27129667e-02, -3.47139835e-02,  3.42463367e-02,
         2.25774981e-02,  1.19847059e-03,  1.92240737e-02,
        -8.12556595e-03, -1.78078040e-02, -1.01359934e-03,
        -4.44382802e-02],
       [-1.27129667e-02, -3.47139835e-02,  3.42463367e-02,
         2.25774981e-02,  1.19847059e-03,  1.92240737e-02,
        -8.12556595e-03, -1.78078040e-02, -1.01359934e-03,
        -4.44382802e-02],
       [-1.27129667e-02, -3.47139835e-02,  3.42463367e-02,
         2.25774981e-02,  1.19847059e-03,  1.92240737e-02,
        -8.12556595e-03, -1.78078040e-02, -1.01359934e-03,
        -4.44382802e-02],
       [ 3.97885554e-02,  8.18595290e-05, -2.96142343e-02,
         3.56568731e-02, -4.90305200e-02, -4.94892001e-02,
         4.91443314e-02, -2.06935890e-02,  3.76176350e-02,
        -1.